# -*- coding: utf-8 -*-
"""quadratic function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVuLn8BosfIOkP3iSLSrzbATmprvkU7z
"""

import numpy as np
import matplotlib.pyplot as plt


def quadratic_function(x):
  return x**2
x = np.linspace(-10, 10,100 )
y = quadratic_function(x)
plt.plot(x, y, label="y = x^2")
plt.title("Linear Function")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Define the function f(x) = x^2
def quadratic_function(x):
    return x**3

# Generate x values (e.g., from -10 to 10)
x = np.linspace(-10, 10, 100)

# Calculate the corresponding y values for f(x) = x^2 COPIED FROM INTERNET
y = quadratic_function(x)

# Plot the quadratic function
plt.plot(x, y, label="y = x^3")
plt.title("Quadratic Function: f(x) = x^3")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.legend()
plt.show()





import numpy as np
import matplotlib.pyplot as plt

def quadratic_function(x):
  return 1/x

x=np.linspace(-10,10,100)

y=quadratic_function(x)
plt.plot(x, y, label= "y=x**4")
plt.title("quadratic function")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend(loc="best")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def quadratic_function(x):
  return np.abs(x)

x=np.linspace(-10,10,100)

y=quadratic_function(x)
plt.plot(x, y, label= "y=|x|")
plt.title("quadratic function")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.legend(loc="best")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Define the function f(x) = x^2
def sine_function(x):
    return np.sin(x)

# Generate x values (e.g., from -10 to 10)
x = np.linspace(-10, 10, 100)

y = sine_function(x)

# Plot the quadratic function
plt.plot(x, y, label="y = sin(x)")
plt.title("Quadratic Function: f(x) = sin(x)")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define the function f(x, y)
def f(x, y):
    return 0.5 * (x - 3)**2 + 0.3 * (y + 1)**2

# Generate x and y values (e.g., from -10 to 10)
x = np.linspace(-10, 10, 100)
y = np.linspace(-10, 10, 100)

# Create a meshgrid to plot the function
X, Y = np.meshgrid(x, y)
Z = f(X, Y)

# Create the 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
ax.plot_surface(X, Y, Z, cmap='viridis')

# Add labels and title
ax.set_title("Surface Plot of f(x, y) = 1/2(x-3)^2 + 0.3(y+1)^2")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("f(x, y)")

# Show the plot
plt.show()