# -*- coding: utf-8 -*-
"""Scripts.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POPvqyg-ksTeR-gBlYLx0DHpqW0lPDc6
"""

#Script1

def to_celsius(f):
    if f < -459.67:
        raise ValueError("Below absolute zero")
    return (f - 32) * 5/9

def main():
    temp_f = 96
    temp_c = to_celsius(temp_f)
    print("Celsius:", temp_c)

if __name__ == "__main__":
    main()



#script2

def avg(nums):
    if not nums:
        return 0
    return sum(nums) / len(nums)

def main():
    values = [3, 7, 10]
    print("Average:", avg(values))

if __name__ == "__main__":
    main()

#script3

def count_lines(path):
    with open(path) as f:
        return sum(1 for _ in f)

def main():
    try:
        print("Lines:", count_lines("data.txt"))
    except FileNotFoundError:
        print("File missing.")

if __name__ == "__main__":
    main()



#script4

def add(a, b):
    return a + b

def main():
    x, y = 4, 7
    if x > 0:
        print("Sum:", add(x, y))

if __name__ == "__main__":
    main()



#script5

def find_max(nums):
    if not nums:
        return None
    return max(nums)

def main():
    arr = [2, 9, 4]
    print(find_max(arr))

if __name__ == "__main__":
    main()



#Script6

def reverse(s):
    if not s:
        return s
    return s[::-1]

def main():
    print(reverse("hello"))

if __name__ == "__main__":
    main()



#Script7

def safe_div(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None

def main():
    result = safe_div(10, 0)
    print("Result:", result)

if __name__ == "__main__":
    main()



#Script8

def is_even(n):
    return n % 2 == 0

def main():
    num = 13
    if is_even(num):
        print("Even")
    else:
        print("Odd")

if __name__ == "__main__":
    main()



#Script9

def login(user, pwd):
    if pwd == "1234":
        return True
    return False

def main():
    status = login("alice", "1234")
    print("Login success:", status)

if __name__ == "__main__":
    main()



#script10

def get_price(items, key):
    if key not in items:
        return None
    return items[key]

def main():
    prices = {"pen": 2, "book": 5}
    print(get_price(prices, "book"))

if __name__ == "__main__":
    main()



#script11

import numpy as np
import matplotlib.pyplot as plt

def quadratic_function(x):
    """Return the value of a quadratic function y = x^2."""
    return x ** 2

def plot_quadratic(x, y):
    """Plot the quadratic curve."""
    plt.plot(x, y, label="y = x^2")
    plt.title("Quadratic Function Plot")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.grid(True)
    plt.legend()
    plt.show()

def main():
    x = np.linspace(-10, 10, 100)
    y = quadratic_function(x)
    plot_quadratic(x, y)

if __name__ == "__main__":
    main()



#script12

import numpy as np
import matplotlib.pyplot as plt

def cubic_function(x):
    """Compute f(x) = x^3 for an array of values."""
    return x ** 3

def generate_values(start, end, steps=100):
    """Generate evenly spaced x values."""
    if steps <= 0:
        raise ValueError("Number of steps must be positive")
    return np.linspace(start, end, steps)

def plot_function(x, y):
    """Plot a cubic function."""
    plt.plot(x, y, label="y = x^3")
    plt.title("Cubic Function: f(x) = x^3")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.grid(True)
    plt.legend()
    plt.show()

def main():
    try:
        x = generate_values(-10, 10, 100)
        y = cubic_function(x)
        plot_function(x, y)
    except Exception as e:
        # Handles any unexpected runtime errors
        print("An error occurred:", e)

if __name__ == "__main__":
    main()



#script13

import numpy as np
import matplotlib.pyplot as plt

def reciprocal_function(x):
    """Compute f(x) = 1/x safely for an array of values."""
    # Avoid division by zero by replacing 0 with a very small number
    x_safe = np.where(x == 0, 1e-8, x)
    return 1 / x_safe

def generate_values(start, end, steps=100):
    """Generate evenly spaced x values."""
    if steps <= 0:
        raise ValueError("Steps must be positive")
    return np.linspace(start, end, steps)

def plot_function(x, y):
    """Plot the reciprocal function with labels and grid."""
    plt.plot(x, y, label="y = 1/x")
    plt.title("Reciprocal Function: f(x) = 1/x")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.grid(True)
    plt.legend()
    plt.show()

def main():
    try:
        x = generate_values(-10, 10, 100)
        y = reciprocal_function(x)
        plot_function(x, y)
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()



#script14

import numpy as np
import matplotlib.pyplot as plt

def sine_function(x):
    """Compute f(x) = sin(x) for an array of values."""
    return np.sin(x)

def generate_values(start, end, steps=100):
    """Generate evenly spaced x values."""
    if steps <= 0:
        raise ValueError("Steps must be positive")
    return np.linspace(start, end, steps)

def plot_sine(x, y):
    """Plot the sine function with proper labels and styling."""
    plt.plot(x, y, label="y = sin(x)")
    plt.title("Sine Function: f(x) = sin(x)")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.grid(True)
    plt.legend()
    plt.show()

def main():
    try:
        x = generate_values(-10, 10, 100)
        y = sine_function(x)
        plot_sine(x, y)
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()



#script15

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 - needed for 3D plots

def surface_function(x, y):
    """Compute f(x, y) = 0.5(x - 3)^2 + 0.3(y + 1)^2."""
    return 0.5 * (x - 3) ** 2 + 0.3 * (y + 1) ** 2

def generate_grid(start=-10, end=10, steps=100):
    """Generate a meshgrid of x and y values."""
    if steps <= 0:
        raise ValueError("Steps must be positive")
    x = np.linspace(start, end, steps)
    y = np.linspace(start, end, steps)
    return np.meshgrid(x, y)

def plot_surface(X, Y, Z):
    """Create a 3D surface plot."""
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.plot_surface(X, Y, Z, cmap="viridis")
    ax.set_title("Surface Plot of f(x, y) = 0.5(x-3)^2 + 0.3(y+1)^2")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("f(x, y)")
    plt.show()

def main():
    try:
        X, Y = generate_grid(-10, 10, 100)
        Z = surface_function(X, Y)
        plot_surface(X, Y, Z)
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()